# Generated by Django 6.0.2 on 2026-02-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight_lbs', models.IntegerField(default=0)),
                ('weight_oz', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('from_first_name', models.CharField(blank=True, max_length=100)),
                ('from_last_name', models.CharField(blank=True, max_length=100)),
                ('from_address', models.CharField(blank=True, max_length=200)),
                ('from_address2', models.CharField(blank=True, max_length=200)),
                ('from_city', models.CharField(blank=True, max_length=100)),
                ('from_zip', models.CharField(blank=True, max_length=10)),
                ('from_state', models.CharField(blank=True, max_length=2)),
                ('to_first_name', models.CharField(max_length=100)),
                ('to_last_name', models.CharField(max_length=100)),
                ('to_address', models.CharField(max_length=200)),
                ('to_address2', models.CharField(blank=True, max_length=200)),
                ('to_city', models.CharField(max_length=100)),
                ('to_zip', models.CharField(max_length=10)),
                ('to_state', models.CharField(max_length=2)),
                ('weight_lbs', models.IntegerField(default=0)),
                ('weight_oz', models.IntegerField(default=0)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phone_num1', models.CharField(blank=True, max_length=20)),
                ('phone_num2', models.CharField(blank=True, max_length=20)),
                ('order_no', models.CharField(max_length=100)),
                ('item_sku', models.CharField(blank=True, max_length=100)),
                ('shipping_service', models.CharField(default='ground', max_length=50)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('account_balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
            ],
        ),
    ]
