# Generated by Django 6.0.2 on 2026-02-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentrecord',
            name='from_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shipmentrecord',
            name='from_zip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shipmentrecord',
            name='to_state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipmentrecord',
            name='to_zip',
            field=models.CharField(max_length=50),
        ),
    ]
